FROM nginx:alpine

COPY nginx_tunning.conf /etc/nginx/nginx.conf
COPY nginx.conf /etc/nginx/conf.d/default.conf

## Remove default nginx website
RUN rm -rf /usr/share/nginx/html/*

RUN apk update
RUN apk upgrade

## From ‘builder’ stage copy over the artifacts in dist folder to default nginx public folder

COPY target/site/serenity /usr/share/nginx/html

CMD ["nginx", "-g", "daemon off;"]